@startuml

actor Admin
actor User

Admin -> Dockerfile :Build
Dockerfile -> load_things : Download models
Dockerfile -> webserver.server : Run

User -> webserver.server : Ask question

webserver.server -> RAG_Model : Question

RAG_Model -> steps.vectorstore.load_or_create_vectorstore : Ask similars

steps.vectorstore.load_or_create_vectorstore -> steps.load_data.make_splits : Load Documents into DB

steps.load_data.make_splits --> steps.vectorstore.load_or_create_vectorstore : List of Documents

steps.vectorstore.load_or_create_vectorstore --> RAG_Model : vectorestore (ChromaDB)
RAG_Model -> steps.answer_question_llm : Ask LLM Model
steps.answer_question_llm -> RAG_Model : Answer, docs
RAG_Model -> webserver.server : Answer, docs

webserver.server -> User : Answer, docs

@enduml