@startuml
allowmixing



class RAG_Model {
rag_model_function(self, prompt1, prompt2)
}

class load_things {
}
folder steps {
class load_data {
    make_splits()
    }
class utils {
get_chunks() -> List[str]
}
class vectorstore{
make_vectorstore()
load_vectorstore()
load_or_create_vectorstore()
}
class Answer{
    answer_question_llamacpp()
    answer_question_mt5()

}

}

folder config {
class config {

}
class config_class {

}
file configuration.yaml {

}
}



folder webserver {
class server {

}
folder templates {
file index.html {

}
file config.html {
    
}
}
}

folder models
folder data






() langchain
() flask
() flask_socketio
() transformers
() tiktoken
() chromadb


Answer ---> langchain
server --> flask
server --> flask_socketio
load_data ---> langchain
vectorstore ---> langchain
vectorstore -> chromadb
load_data --> tiktoken

config <-- load_data
config <-- RAG_Model
vectorstore <-- RAG_Model
load_data <-- vectorstore

load_data --> utils

vectorstore --> models
RAG_Model ---> Answer
load_data --> data
Answer ---> models

server --> RAG_Model
server --> index.html
server --> config.html

@enduml